### ISSUE TITLE
Signups Forbidden

### ISSUE THREAD

**Issue by digitzfone** [matteodem/orion-cli#12] opened 2015-03-03 04:55 UTC
I have created a site using orion-cli. One of the first things I do is a reset to clear out the demo code and remove autopublish. However, using accounts-base and accounts-password, every time i try to create an account I get a "Signups forbidden" message. This is not a problem when I do an app without orion-cli.  I have added the line "Accounts.config({var forbidClientAccountCreation = false;})" and it has no bearing, Signups are still forbidden. Any help on this would be appreciated greatly!!

**Comment by matteodem** [comment] 2015-03-03 06:22
What profile are you using?

**Comment by digitzfone** [comment] 2015-03-03 19:42
Coffeescript

**Comment by matteodem** [comment] 2015-03-03 19:54
can you provide a reproduction repo?

**Comment by digitzfone** [comment] 2015-03-03 21:56
This should do it…

https://bitbucket.org/digitzfone/edify <https://bitbucket.org/digitzfone/edify>

**Comment by digitzfone** [comment] 2015-03-05 22:27
Hey Matteo, thanks for working on this with me. Do you believe this is a bug in orion or with the accounts api?

**Comment by matteodem** [comment] 2015-07-22 17:44
Is this fixed?

**Comment by matteodem** [comment] 2015-10-14 14:28
This has to do with `useraccounts:semantic-ui`, see https://github.com/matteodem/meteor-boilerplate/issues/94. I'll close this as it's a dupe

**Closed by matteodem** 2015-10-14 14:28 UTC
Labels: bug
